# Generated by Django 5.0.8 on 2024-08-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_agent_agent_surname_alter_agent_agent_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='svg_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
