# Generated by Django 5.0.8 on 2024-08-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_portfolioimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='cretae_date',
            new_name='creted_date',
        ),
    ]
