# Generated by Django 5.0.8 on 2024-08-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_cretae_date_portfolio_creted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='creted_date',
            new_name='cretae_date',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
