# Generated by Django 5.0.8 on 2024-08-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_creted_date_portfolio_cretae_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='cretae_date',
            new_name='created_date',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.portfolio')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
