# Generated by Django 5.0.8 on 2024-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_cretae_date_portfolio_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Portfolio Image'),
        ),
    ]
