# Generated by Django 5.1 on 2024-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=20)),
                ('com_email', models.EmailField(max_length=40)),
                ('com_message', models.CharField(max_length=300)),
                ('com_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
